# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 60, 350, 490))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgb(208, 206, 226);\n"
"border-radius: 25px;\n"
"border: 2px solid rgb(141, 137, 171);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(55, 380, 240, 40))
        self.label.setStyleSheet("color: #000000;\n"
"font: 14pt \"幼圆\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(55, 412, 240, 40))
        self.label_2.setStyleSheet("color: #000000;\n"
"font: 14pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(133, 461, 84, 25))
        self.label_3.setStyleSheet("color: #000000;\n"
"font: 10pt \"Georgia\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(85, 40, 180, 40))
        self.label_4.setStyleSheet("color: #000000;\n"
"font: 12pt \"Georgia\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(45, 70, 260, 40))
        self.label_5.setStyleSheet("color: #000000;\n"
"font: 12pt \"Georgia\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(145, 100, 60, 40))
        self.label_6.setStyleSheet("color: #000000;\n"
"font: 12pt \"Georgia\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 130, 290, 40))
        self.label_7.setStyleSheet("color: #000000;\n"
"font: 12pt \"Georgia\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 200, 150, 150))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/myicon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(390, 90, 330, 430))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top: 2px solid rgb(141, 137, 171);\n"
"border-right: 2px solid rgb(141, 137, 171);\n"
"border-bottom: 2px solid rgb(141, 137, 171);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(270, 10, 61, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"border: none;\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom: 5px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(0, 50, 330, 350))
        self.frame_6.setMinimumSize(QtCore.QSize(330, 350))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 2px solid rgb(141, 137, 171);\n"
"    border-radius: 10px;\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(123, 120, 150);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_L_account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_account.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_L_account.setObjectName("lineEdit_L_account")
        self.verticalLayout_4.addWidget(self.lineEdit_L_account)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_L_password.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_password.setSizePolicy(sizePolicy)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.verticalLayout_4.addWidget(self.lineEdit_L_password)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_4.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_R_account = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_account.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_R_account.setObjectName("lineEdit_R_account")
        self.verticalLayout_5.addWidget(self.lineEdit_R_account)
        self.lineEdit_R_password_1 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password_1.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_R_password_1.setObjectName("lineEdit_R_password_1")
        self.verticalLayout_5.addWidget(self.lineEdit_R_password_1)
        self.lineEdit_R_password_2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_R_password_2.setObjectName("lineEdit_R_password_2")
        self.verticalLayout_5.addWidget(self.lineEdit_R_password_2)
        self.pushButton_R_sure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_5.addWidget(self.pushButton_R_sure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.horizontalLayout_2.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("QPushButton{\n"
"    font: 10pt \"幼圆\";\n"
"    border: none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(123, 120, 150);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout.setContentsMargins(11, 0, -1, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_Login.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Login.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon2)
        self.pushButton_Login.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_Register.setStyleSheet("")
        self.pushButton_Register.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon3)
        self.pushButton_Register.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("QLabel {\n"
"    \n"
"    font: 9pt \"幼圆\";\n"
"    color: rgb(187,90,78);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.page_7)
        self.label_13.setStyleSheet("color: rgb(20, 131, 139);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "光学相机通信干扰下的"))
        self.label_2.setText(_translate("LoginWindow", "可靠智能手势识别系统"))
        self.label_3.setText(_translate("LoginWindow", "Version 1.0"))
        self.label_4.setText(_translate("LoginWindow", "The Reliable Smart"))
        self.label_5.setText(_translate("LoginWindow", "Gesture Recognition System"))
        self.label_6.setText(_translate("LoginWindow", "under"))
        self.label_7.setText(_translate("LoginWindow", "0ptical Camera Communication"))
        self.lineEdit_L_account.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.lineEdit_L_password.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.pushButton_L_sure.setText(_translate("LoginWindow", "确 认 登 录"))
        self.lineEdit_R_account.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.lineEdit_R_password_1.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.lineEdit_R_password_2.setPlaceholderText(_translate("LoginWindow", "请再次输入密码以确认"))
        self.pushButton_R_sure.setText(_translate("LoginWindow", "确 认 注 册"))
        self.label_8.setText(_translate("LoginWindow", "账号或密码不得为空"))
        self.label_9.setText(_translate("LoginWindow", "账号不存在"))
        self.label_10.setText(_translate("LoginWindow", "密码错误"))
        self.label_11.setText(_translate("LoginWindow", "两次输入的密码不一致"))
        self.label_12.setText(_translate("LoginWindow", "用户名重复"))
        self.label_13.setText(_translate("LoginWindow", "注册成功"))
import res_rc
