# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 50, 900, 606))
        self.frame.setMinimumSize(QtCore.QSize(900, 600))
        self.frame.setStyleSheet("#frame {\n"
"    border: 2px solid rgb(96, 91, 134);\n"
"    border-radius: 22px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(96, 91, 134);\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"幼圆\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/myicon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(36, 36))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    padding-bottom: 5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_3.addWidget(self.pushButton_logout)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/close2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6 {\n"
"    background-color: rgb(208, 206, 226);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border: 2px solid rgb(208, 206, 226)\n"
"}\n"
"QPushButton {\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.pushButton_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_info.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_info.setObjectName("pushButton_info")
        self.verticalLayout_2.addWidget(self.pushButton_info)
        self.pushButton_reco = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_reco.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_reco.setObjectName("pushButton_reco")
        self.verticalLayout_2.addWidget(self.pushButton_reco)
        self.pushButton_other = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_other.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_other.setObjectName("pushButton_other")
        self.verticalLayout_2.addWidget(self.pushButton_other)
        self.pushButton_fqa = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_fqa.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fqa.setObjectName("pushButton_fqa")
        self.verticalLayout_2.addWidget(self.pushButton_fqa)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_my.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_2.addWidget(self.pushButton_my)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7 {\n"
"    border-bottom-right-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setStyleSheet("font: 75 20pt \"Georgia\";")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_home)
        self.pushButton_10.setStyleSheet("border: none;")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.page_home)
        self.label_2.setStyleSheet("font: 20pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page_home)
        self.page_info = QtWidgets.QWidget()
        self.page_info.setObjectName("page_info")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_info)
        self.plainTextEdit.setGeometry(QtCore.QRect(12, 19, 660, 500))
        self.plainTextEdit.setMinimumSize(QtCore.QSize(660, 500))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(660, 500))
        self.plainTextEdit.setStyleSheet("#plainTextEdit{\n"
"    font: 10pt \"幼圆\";\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    margin:0px 0px 0px 0px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:0px;\n"
"    width:21px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(208, 206, 226);\n"
"    border-radius:10px;\n"
"    width:20px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"subcontrol-position:top;\n"
"subcontrol-origin:margin;\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid rgb(255, 255, 255);\n"
"height:16px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"subcontrol-position:bottom;\n"
"subcontrol-origin:margin;\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid rgb(255, 255, 255);\n"
"height:16px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical{\n"
"    width:0px;\n"
"    height:0px;\n"
"}\n"
"QScrollBar::down-arrow:vertical{\n"
"    width:0px;\n"
"    height:0px;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical,QScrollBar::add-page:vertical{\n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.stackedWidget.addWidget(self.page_info)
        self.page_reco = QtWidgets.QWidget()
        self.page_reco.setObjectName("page_reco")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_reco)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_16 = QtWidgets.QFrame(self.page_reco)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(123, 120, 150);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_R_sure = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(500, 50))
        self.pushButton_R_sure.setMaximumSize(QtCore.QSize(500, 50))
        self.pushButton_R_sure.setStyleSheet("")
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_14.addWidget(self.pushButton_R_sure)
        self.verticalLayout_13.addWidget(self.frame_17, 0, QtCore.Qt.AlignHCenter)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setStyleSheet("QLabel {\n"
"    border: 6px solid rgb(208, 206, 226);\n"
"    border-radius: 6px;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_R_raw = QtWidgets.QLabel(self.frame_20)
        self.label_R_raw.setMinimumSize(QtCore.QSize(230, 230))
        self.label_R_raw.setMaximumSize(QtCore.QSize(230, 230))
        self.label_R_raw.setText("")
        self.label_R_raw.setObjectName("label_R_raw")
        self.horizontalLayout_8.addWidget(self.label_R_raw)
        self.label_R_new = QtWidgets.QLabel(self.frame_20)
        self.label_R_new.setMinimumSize(QtCore.QSize(230, 230))
        self.label_R_new.setMaximumSize(QtCore.QSize(230, 230))
        self.label_R_new.setText("")
        self.label_R_new.setObjectName("label_R_new")
        self.horizontalLayout_8.addWidget(self.label_R_new)
        self.verticalLayout_15.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("QLabel {\n"
"    \n"
"    font: 10pt \"幼圆\";\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setMinimumSize(QtCore.QSize(230, 0))
        self.label_5.setMaximumSize(QtCore.QSize(230, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_21)
        self.label_6.setMinimumSize(QtCore.QSize(230, 0))
        self.label_6.setMaximumSize(QtCore.QSize(230, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_15.addWidget(self.frame_21, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame_19)
        self.stackedWidget_3.setStyleSheet("font: 11pt \"幼圆\";\n"
"")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page__0 = QtWidgets.QWidget()
        self.page__0.setObjectName("page__0")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page__0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.stackedWidget_3.addWidget(self.page__0)
        self.page__1 = QtWidgets.QWidget()
        self.page__1.setObjectName("page__1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page__1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.page__1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__1)
        self.page__2 = QtWidgets.QWidget()
        self.page__2.setObjectName("page__2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.page__2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.page__2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__2)
        self.page__3 = QtWidgets.QWidget()
        self.page__3.setObjectName("page__3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.page__3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.page__3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__3)
        self.page__4 = QtWidgets.QWidget()
        self.page__4.setObjectName("page__4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page__4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.page__4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__4)
        self.page__5 = QtWidgets.QWidget()
        self.page__5.setObjectName("page__5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page__5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.page__5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_17.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__5)
        self.page__6 = QtWidgets.QWidget()
        self.page__6.setObjectName("page__6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.page__6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.page__6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page__6)
        self.horizontalLayout_18.addWidget(self.stackedWidget_3)
        self.verticalLayout_13.addWidget(self.frame_19)
        self.verticalLayout_12.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_reco)
        self.page_other = QtWidgets.QWidget()
        self.page_other.setObjectName("page_other")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_other)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.page_other)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(208, 206, 226);\n"
"}\n"
"QFrame:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    border:none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_O_dataset = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_O_dataset.sizePolicy().hasHeightForWidth())
        self.pushButton_O_dataset.setSizePolicy(sizePolicy)
        self.pushButton_O_dataset.setMinimumSize(QtCore.QSize(0, 233))
        self.pushButton_O_dataset.setMaximumSize(QtCore.QSize(16777215, 233))
        self.pushButton_O_dataset.setObjectName("pushButton_O_dataset")
        self.verticalLayout_9.addWidget(self.pushButton_O_dataset)
        self.horizontalLayout_6.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(208, 206, 226);\n"
"}\n"
"QFrame:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    border:none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_O_model = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_O_model.setMinimumSize(QtCore.QSize(0, 233))
        self.pushButton_O_model.setMaximumSize(QtCore.QSize(16777215, 233))
        self.pushButton_O_model.setObjectName("pushButton_O_model")
        self.verticalLayout_10.addWidget(self.pushButton_O_model)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.verticalLayout_8.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(208, 206, 226);\n"
"}\n"
"QFrame:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    border:none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_O_ros = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_O_ros.setMinimumSize(QtCore.QSize(0, 233))
        self.pushButton_O_ros.setMaximumSize(QtCore.QSize(16777215, 233))
        self.pushButton_O_ros.setObjectName("pushButton_O_ros")
        self.verticalLayout_11.addWidget(self.pushButton_O_ros)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("QFrame {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(208, 206, 226);\n"
"}\n"
"QFrame:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    border:none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(96, 91, 134);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_O_doc = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_O_doc.setMinimumSize(QtCore.QSize(0, 233))
        self.pushButton_O_doc.setMaximumSize(QtCore.QSize(16777215, 233))
        self.pushButton_O_doc.setObjectName("pushButton_O_doc")
        self.horizontalLayout_7.addWidget(self.pushButton_O_doc)
        self.horizontalLayout_5.addWidget(self.frame_15)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_other)
        self.page_fqa = QtWidgets.QWidget()
        self.page_fqa.setObjectName("page_fqa")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.page_fqa)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(12, 19, 656, 500))
        self.plainTextEdit_2.setMinimumSize(QtCore.QSize(656, 500))
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(656, 500))
        self.plainTextEdit_2.setStyleSheet("#plainTextEdit_2{\n"
"    font: 10pt \"幼圆\";\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    margin:0px 0px 0px 0px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:0px;\n"
"    width:21px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(208, 206, 226);\n"
"    border-radius:10px;\n"
"    width:20px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(96, 91, 134);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"subcontrol-position:top;\n"
"subcontrol-origin:margin;\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid rgb(255, 255, 255);\n"
"height:16px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"subcontrol-position:bottom;\n"
"subcontrol-origin:margin;\n"
"background-color:rgb(255, 255, 255);\n"
"border:1px solid rgb(255, 255, 255);\n"
"height:16px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical{\n"
"    width:0px;\n"
"    height:0px;\n"
"}\n"
"QScrollBar::down-arrow:vertical{\n"
"    width:0px;\n"
"    height:0px;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical,QScrollBar::add-page:vertical{\n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.stackedWidget.addWidget(self.page_fqa)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_my)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.page_my)
        self.frame_8.setMinimumSize(QtCore.QSize(340, 520))
        self.frame_8.setMaximumSize(QtCore.QSize(340, 520))
        self.frame_8.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 2px solid rgb(141, 137, 171);\n"
"    border-radius: 10px;\n"
"    font: 11pt \"幼圆\";\n"
"}\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(208, 206, 226);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(123, 120, 150);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 5px;\n"
"    padding-left: 5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.lineEdit_M_pass_1 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_M_pass_1.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_M_pass_1.setObjectName("lineEdit_M_pass_1")
        self.verticalLayout_6.addWidget(self.lineEdit_M_pass_1)
        self.lineEdit_M_pass_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_M_pass_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_M_pass_2.setObjectName("lineEdit_M_pass_2")
        self.verticalLayout_6.addWidget(self.lineEdit_M_pass_2)
        self.pushButton_M_sure = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_M_sure.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_M_sure.setObjectName("pushButton_M_sure")
        self.verticalLayout_6.addWidget(self.pushButton_M_sure)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.stackedWidget_2.setStyleSheet("QLabel {\n"
"    \n"
"    font: 9pt \"幼圆\";\n"
"    color: rgb(187,90,78);\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setStyleSheet("color: rgb(20,131,139);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_6.addWidget(self.stackedWidget_2)
        self.verticalLayout_5.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_my)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "光学相机通信干扰下的可靠智能手势识别系统"))
        self.pushButton_home.setText(_translate("MainWindow", "系统首页"))
        self.pushButton_info.setText(_translate("MainWindow", "项目简介"))
        self.pushButton_reco.setText(_translate("MainWindow", "手势识别"))
        self.pushButton_other.setText(_translate("MainWindow", "可用扩展"))
        self.pushButton_fqa.setText(_translate("MainWindow", "常见问题"))
        self.pushButton_my.setText(_translate("MainWindow", "用户设置"))
        self.label.setText(_translate("MainWindow", "Welcome to the System"))
        self.label_2.setText(_translate("MainWindow", "欢迎登录"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "    近年来，随着物联网科技的发展，光学相机通信受到了相关研究人员的广泛关注，因为它同时具有可用频谱的丰富性和部署的便捷性的优势。然而，该技术的使用导致了信号接收方或场景内其他设备的嵌入式摄像机捕获的视频或图像数据受到可见光通信信号的干扰。传统的数字图像信号和可见光通信信号混合后叠加在一起，导致了智能机器在执行原有的计算机视觉任务时受到严重影响，其效率和精度都有显著的降低。\n"
"    以未来的智能家居或医疗保健领域为例，各种移动机器人被设计和开发用于辅助人类的日常活动，它们大多需要在使用光学摄像机和可见光通信技术实现个体之间的信息传输的同时，利用同一个摄像机捕获的视频或图像作为输入源，执行各种计算机视觉领域的功能，如物体识别与分类、目标检测和追踪、图像分割和处理等。其中，基于计算机视觉的非接触式手势识别是这些任务中重要的一部分，也是被广泛采用的一项用于控制以移动机器人为代表的各种自主系统和智能设备的手段。\n"
"    然而，移动机器人自身的嵌入式摄像机在这个场景下不可避免的既捕获了用于通信的光通信信号，也捕获了包含有手势信息的数字图像信号，即常规的手势照片。可见光通信信号叠加在和手势及背景的同一个二维图像数组上，具体表现为捕获的图像里出现若干黑色竖状条纹，破坏了图像的完整性及其原有统计结构，对高效率高精度的手势识别带来了显著挑战。同时，手势和复杂背景的存在，也对通信功能带来了干扰。因此，通过某种技术手段对两种信号进行解码，将它们分解并复原出清晰的图像，不仅可以提高手势识别的效果，还能通过计算原有受干扰的图像和复原后的清晰图像之间的残差，增强光学相机通信功能的稳健性。\n"
"    该类先通过图像重构再进行残差计算的信号解码分离技术的应用领域也不仅局限于智能家居或医疗保健场景下的移动机器人，任何同时涉及到光学相机通信和计算机视觉手势识别控制的场景，均可以应用此项技术。例如，在工厂中的机械臂和室外环境下的小型无人机的手势控制等领域，解决光学图像信号和可见光通信信号叠加问题将为自动化进程提供更强大、更灵活和更智能的控制方式。所以，在以手势图像重构作为信号解码的第一步的技术路线中，设计和开发专业且先进的图像重构算法显得尤为重要。\n"
"    综上所述，此项研究聚焦于可见光相机通信干扰下的基于计算机视觉的手势识别。通过改良和设计专用的图像重构算法，从光学图像信号和可见光通信信号的混叠矩阵中分离并重构出清晰的手势图片，以提高手势识别算法的精确性，提升以移动机器人为代表的一类智能设备的效能及用户体验。同时，重构后清晰的图片也客观上有助于对光学相机通信功能的改进。这一研究的意义不仅在于改善现有技术使用中的问题，还在于推动可见光通信和计算机视觉的融合，由于缓解了光通信信号对原有算法和功能的干扰，可见光通信技术可以更为广泛的部署在智能边缘设备中，相应的拓展了各种智能设备的功能。随着智能家居、智能城市和工业4.0等概念的不断发展，各种智能设备将在我们的生活中扮演越来越重要的角色。通过重构图像出清晰的图像以解决背景图像和可见光相机通信信号的叠加问题，我们可以更加方便的部署更多的智能设备，这将给人类的日常工作生活带来更多的便利，为人们创造出更好的生活环境，为人类创造更智能、更便利的未来。"))
        self.pushButton_R_sure.setText(_translate("MainWindow", "点击此处以上传图像完成重构及识别"))
        self.label_5.setText(_translate("MainWindow", " 重构前..."))
        self.label_6.setText(_translate("MainWindow", " 重构后..."))
        self.label_9.setText(_translate("MainWindow", "--- 手势 0 ---"))
        self.label_10.setText(_translate("MainWindow", "--- 手势 1 ---"))
        self.label_11.setText(_translate("MainWindow", "--- 手势 2 ---"))
        self.label_12.setText(_translate("MainWindow", "--- 手势 3 ---"))
        self.label_13.setText(_translate("MainWindow", "--- 手势 4 ---"))
        self.label_14.setText(_translate("MainWindow", "--- 手势 5 ---"))
        self.pushButton_O_dataset.setText(_translate("MainWindow", "数 据 集 下 载"))
        self.pushButton_O_model.setText(_translate("MainWindow", "模 型 下 载"))
        self.pushButton_O_ros.setText(_translate("MainWindow", "ROS 功 能 包 下 载"))
        self.pushButton_O_doc.setText(_translate("MainWindow", "说 明 文 档"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "1)如何使用该系统？\n"
"\n"
"    点击左侧导航栏“手势识别”选项，根据右侧的提示上传一张受到光学相机通信干扰的图片，点击以确认进行图像重构和手势识别，模型输出的结果将展示在屏幕上。\n"
"\n"
"2）算法是否可以部署在边缘端？\n"
"\n"
"    目前本项目正在向边缘端移植，根据计划，将尽快开发一个在 ROS 机器人操作系统上运行的功能包。开发完成后将发布到“可用扩展”中给出的 GitHub 软件仓库中。\n"
"\n"
"3）模型及训练集是否公开？\n"
"\n"
"    模型结构、参数权重文件和训练集放置于“可用扩展”中给出的百度网盘分享链接中。\n"
"\n"
"4）研究背景及意义是什么？\n"
"\n"
"    见“项目简介”模块。\n"
"\n"
"5）用户设置有什么功能？\n"
"\n"
"    修改密码。"))
        self.label_3.setText(_translate("MainWindow", "本页面用于设置新的用户密码："))
        self.lineEdit_M_pass_1.setPlaceholderText(_translate("MainWindow", "请输入新密码"))
        self.lineEdit_M_pass_2.setPlaceholderText(_translate("MainWindow", "请再次输入新密码以确认"))
        self.pushButton_M_sure.setText(_translate("MainWindow", "确 认 修 改 密 码"))
        self.label_4.setText(_translate("MainWindow", "输入不能为空"))
        self.label_7.setText(_translate("MainWindow", "两次输入必须一致"))
        self.label_8.setText(_translate("MainWindow", "修改成功"))
import res_rc
